### PR TITLE
added check statements to perform simple parameter debugging

### PR DESCRIPTION
**Pull request by vignesh1987**
I have added check statements to perform simple checks on some parameters in the OSeMOSYS data file. 
1.'Capacity investment' check
2. 'Annual Activity' check 
3. 'Total capacity' check 
4. 'Minimum Annual activity' check 
5.  'Time Slice' check
6. 'Model period activity limit' check

### CODE REVIEW

**Comment by vignesh1987** [comment]
Hi,
I have now created test cases for the check statements except for statement 3 (**Total capacity check**). I am not able to find a workaround for checking **Total annual max capacity>= residual capacity + Total Annual Min capacity investment**  for those technologies where the Total annual max capacity is not zero by default but intentionally (by mistake) entered as zero. @willu47, @tniet, @abhishek0208 : if any of you have a few minutes, would like to discuss this!

**Comment by tniet** [comment]
Hey @vignesh1987 - Happy to find a time to meet to discuss but the time zone differences might make that challenging.

Looking at the code, why you don't want to check when TotalAnnualMaxCap is 0 (even if it's the default)?  If we adopt the -1 convention of not binding (per commit https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/commit/83f2d80c6bf5e07bd8f9a4ab284f309430463317) then we should be checking for zero TotalAnnualMaxCap against ResidualCap, etc.

Am I missing something?

**Comment by willu47** [comment]
Tests are currently failing because your checks have found a problem in the utopia model!

```ampl
$ glpsol -m src/osemosys.txt -d tests/utopia.txt 
GLPSOL: GLPK LP/MIP Solver, v4.65
Parameter(s) specified in the command line:
 -m src/osemosys.txt -d tests/utopia.txt
Reading model section from src/osemosys.txt...
1097 lines were read
Reading data section from tests/utopia.txt...
543 lines were read
Checking (line 156)...
Capacity investment check successful 
Checking (line 160)...
Annual Activity check successful 
Checking (line 164)...
Capacity check 1 successful 
Checking (line 168)...
Capacity check 2 successful 
Checking (line 172)...
Minimum Activity check successful 
Checking (line 176)...
src/osemosys.txt:176: check[1990] failed
MathProg model processing error
```

**Comment by willu47** [comment]
Suggest something like this:
```ampl
check{y in YEAR}: sum{l in TIMESLICE} YearSplit[l,y] >= 0.9999 && sum{l in TIMESLICE} YearSplit[l,y] <= 1.0001;
```

**Review by willu47 — CHANGES_REQUESTED** [review]
Hi @vignesh1987 - the check statements seem good - the 'Time Slice' (`YearSplit`) check doesn't seem to like the Utopia values, which is why the tests are failing. One suggestion is to move the print statement before the check that it refers to. That way if the check fails, you know why without having to check the osemosys code. Suggest also making the message more information e.g. `Checking YearSlice parameter for y in YEAR:`

Next up, there seem a very large number of changes in the OSeMOSYS code that are in addition to the check statements. A number of variables and pasted out. It looks like you've added the check statements to a custom version of the OSeMOSYS code (albeit based on a recent version).

Could you work from the most recent version of the code on the master branch and add the check statements to that so that the pull request just contains the changes relating to the statements? This may seem a bit pedantic, but it then allows very granular development of the code over time which is well documented.

NB. It looks like it was just one commit (e74b6cf1d4756daa0c22bb0971654cc5acea80c9) that caused the difference to the master branch.  You could just revert this commit using `git revert e74b6cf1d4756daa0c22bb0971654cc5acea80c9` and then push this commit to the branch.

**Comment by vignesh1987** [comment]
@willu47 : Thanks for the help and suggestions. I have
1. Corrected the Printf statements as you suggested. Found out that there is a 100 character limit for Print statements in GNU-Mathprog.
2. Changed the year split bounds 
3. Reverted back to the latest master version (for rest of the code)

**Review by willu47 — APPROVED** [review]
Looks good @vignesh1987

**Comment by vignesh1987** [comment]
Should I add it to other versions of the code as well? (as they have the same parameters). I mean the short and the lastest fast versions?

**Comment by willu47** [comment]
Yes please!

**Pull request merged**
